const { Router } = require('express');
const authRoutes = require('./routes/auth.routes');
const accountRoutes = require('./routes/account.routes');
const usersRoutes = require('./routes/users.routes');
const rolesRoutes = require('./routes/roles.routes');
const permissionsRoutes = require('./routes/permissions.routes');
const productsRoutes = require('./routes/products.routes');
const downloadsRoutes = require('./routes/downloads.routes');
const licensesRoutes = require('./routes/licenses.routes');
const servicesRoutes = require('./routes/services.routes');
const projectsRoutes = require('./routes/projects.routes');
const blogRoutes = require('./routes/blog.routes');
const docsRoutes = require('./routes/docs.routes');
const changelogRoutes = require('./routes/changelog.routes');
const faqRoutes = require('./routes/faq.routes');
const reviewsRoutes = require('./routes/reviews.routes');
const supportRoutes = require('./routes/support.routes');
const contactRoutes = require('./routes/contact.routes');
const careersRoutes = require('./routes/careers.routes');
const applicationsRoutes = require('./routes/applications.routes');
const teamRoutes = require('./routes/team.routes');
const companyRoutes = require('./routes/company.routes');
const partnersRoutes = require('./routes/partners.routes');
const subsidiariesRoutes = require('./routes/subsidiaries.routes');
const roadmapRoutes = require('./routes/roadmap.routes');
const analyticsRoutes = require('./routes/analytics.routes');
const notificationsRoutes = require('./routes/notifications.routes');
const auditRoutes = require('./routes/audit.routes');
const searchRoutes = require('./routes/search.routes');
const systemRoutes = require('./routes/system.routes');
const vaultRoutes = require('./routes/vault.routes');
const mediaRoutes = require('./routes/media.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/account', accountRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/products', productsRoutes);
router.use('/product-categories', productsRoutes.categoriesRouter);
router.use('/product-versions', productsRoutes.versionsRouter);
router.use('/product-files', productsRoutes.filesRouter);
router.use('/downloads', downloadsRoutes);
router.use('/licenses', licensesRoutes);
router.use('/services', servicesRoutes);
router.use('/projects', projectsRoutes);
router.use('/blog', blogRoutes);
router.use('/documentation', docsRoutes);
router.use('/changelog', changelogRoutes);
router.use('/faq', faqRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/support', supportRoutes);
router.use('/contact', contactRoutes);
router.use('/careers', careersRoutes);
router.use('/applications', applicationsRoutes);
router.use('/team', teamRoutes);
router.use('/company', companyRoutes);
router.use('/partners', partnersRoutes);
router.use('/subsidiaries', subsidiariesRoutes);
router.use('/roadmap', roadmapRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/search', searchRoutes);
router.use('/audit', auditRoutes);
router.use('/vault', vaultRoutes);
router.use('/media', mediaRoutes);
router.use('/system', systemRoutes);
router.use('/activity', systemRoutes);

module.exports = router;
